name: 'curso_data_engineering'
version: '1.0.0'

# Configuración general para el proyecto
config-version: 2

# Configuraciones globales
models:
  curso_data_engineering:
  
    # Configuración específica para los modelos dentro de 'curso'

    # Configuración específica para 'base'
 

    # Configuración específica para 'staging'
    staging:
      +materialized: table
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}SILVER_DB"
      +schema: stg

    # Configuración específica para 'marts'
    marts:
      +materialized: table
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}GOLD_DB"

    # Configuración específica para 'core'
      core:
        +schema: core
        +database: "{{ env_var('DBT_ENVIRONMENTS') }}GOLD_DB"
        int:
         +schema: intermediate
         +database: "{{ env_var('DBT_ENVIRONMENTS') }}GOLD_DB"

seeds:
  +schema: seed_data
  +database: "{{ env_var('DBT_ENVIRONMENTS') }}BRONZEDB"

snapshots:
  +transient: false
  +target_database: "{{ env_var('DBT_ENVIRONMENTS') }}SILVER_DB"
  +target_schema: snapshots